version: "3.9"

services:
  web:
    build:
      context: ./services/php
    restart: always
    ports:
      - '9001:9000'
    volumes:
      - ./src:/var/www/html
      - ./services/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: arm64v8/mysql:oracle
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=slim
      - MYSQL_ROOT_PASSWORD=app
    ports:
      - '4306:3306'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db
  # Add rabbitmq image
  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
        - '5672:5672'
        - '15672:15672'
